export const INITIAL_STATE = {
  data: {},
  user: {},
  picked_material: 'aluminium_oxide',
  creating_user: false,
  created_user: false,
  loggin_in_user: false,
  logged_in_user: false,
  authUser: false,
  fetching_Items: false,
  fetched_Item: false,
  adding_Item: false,
  added_Item: false,
  updating_Item: false,
  updated_Item: false,
  deleting_Item: false,
  deleted_Item: false,
  error: null,
};
